targets:
  dev:
    default: true

    workspace:
      host: https://adb-7405614724722402.2.azuredatabricks.net

    variables:
      catalog: dbr_dev
      sql_warehouse_id: "d6092c263a047666"
      landing_storage_location: "abfss://landing@stdatabricksdemo26.dfs.core.windows.net/"

    resources:
      volumes:
        landing_volume:
          name: landing
          catalog_name: ${var.catalog}
          schema_name: ${resources.schemas.bronze.name}
          volume_type: EXTERNAL
          storage_location: ${var.landing_storage_location}