targets:
  dev:
    default: true

    workspace:
      host: https://adb-7405606278809955.15.azuredatabricks.net

    variables:
      catalog: dbr_dev
      sql_warehouse_id: "9d0ad0844cc205a3"
      landing_storage_location: "abfss://landing@dlspldatabricks.dfs.core.windows.net/"

    resources:
      volumes:
        landing_volume:
          name: landing
          catalog_name: ${var.catalog}
          schema_name: ${resources.schemas.bronze.name}
          volume_type: EXTERNAL
          storage_location: ${var.landing_storage_location}