targets:
  dev:
    default: true

    resources:
      volumes:
        landing_volume:
          name: landing
          catalog_name: ${var.catalog}
          schema_name: ${resources.schemas.bronze_schema.name}
          volume_type: MANAGED