targets:
  prod:
    mode: production

    workspace:
      host: https://adb-7405604503619901.1.azuredatabricks.net
      root_path: /Workspace/Users/e3e66ff4-6fc8-42b6-ba09-f592bc7dabc5/.bundle/${bundle.name}/${bundle.target}

    variables:
      catalog: dbr_dev
      sql_warehouse_id: "3ed106620db591d9"
      landing_storage_location: abfss://demo2-prod@dlspl21databricks.dfs.core.windows.net/landing

    resources:
      volumes:
        landing_volume:
          name: landing
          catalog_name: ${var.catalog}
          schema_name: ${resources.schemas.bronze.name}
          volume_type: EXTERNAL
          storage_location: ${var.landing_storage_location}