[project]
name = "ecommerce_pipeline_demo"
version = "0.0.1"
authors = [
    { name = "Yanquiel Gomez", email = "yanquiel@softserve.academy" },
]
requires-python = ">=3.11,<3.12"
dependencies = [
    "databricks-zerobus-ingest-sdk>=1.6.1",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "ipykernel",
]

unit-tests = [
    "pyspark==3.5.0",
]

integration-tests = [
    "databricks-connect>=15.4.10,<15.5",
]

[tool.uv]
package = false
default-groups = ["dev"]

conflicts = [
    [
        { group = "unit-tests" },
        { group = "integration-tests" },
    ],
]

[tool.ruff]
line-length = 120

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
markers = [
    "unit_test: fast isolated tests using local PySpark",
    "integration_test: tests running against Databricks",
]